### ISSUE TITLE
Can I translate your article to chinese and republish to my blog?

### ISSUE THREAD

**Issue by wangerzi** [duhaime/douglasduhaime.com#19]
Hello @duhaime , I found a greate article about cloudfront basic authorization in your website and it's helpful for me.
So I want to translate your article [https://douglasduhaime.com/posts/s3-lambda-auth.html](https://douglasduhaime.com/posts/s3-lambda-auth.html) to chinese and publish to my blog with your original link and original author, but I did not found any licence in your website, is it ok?

**Comment by duhaime** [comment]
@wangerzi Thanks for your kind words! Yes, please feel free to translate the article and post it on your blog. I'll add an MIT license now...

**Comment by wangerzi** [comment]
@duhaime I'm already translate this blog, and this is my first time what I tried to translate an English blog, it cost me about 6 hours, but I'm very excited about it!
Thanks you for writing such a great blog, and this is my translate blog address: https://blog.wj2015.com/?p=608
